<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.fasterxml</groupId>
    <artifactId>oss-parent</artifactId>
    <version>79</version>
  </parent>
  <groupId>com.fasterxml.staxmate</groupId>
  <artifactId>staxmate</artifactId>
  <packaging>bundle</packaging>
  <version>2.5.0-SNAPSHOT</version>

  <name>StaxMate</name>
  <description>
StaxMate is a light-weight framework that adds convenience to streaming XML-processing  without significant additional overhead.
It builds on top of a Stax (JSR-173) compliant XML processors such as Woodstox or Sjsxp (default Stax implementation of JDK 1.6) and offers two basic abstractions: Cursors, which build on XMLStreamReaders and Output objects, which build on XMLStreamWriters.
</description>
 <!-- Contact information -->
  <url>http://staxmate.codehaus.org</url>

  <scm>
    <connection>scm:git:git@github.com:FasterXML/StaxMate.git</connection>
    <developerConnection>scm:git:git@github.com:FasterXML/StaxMate.git</developerConnection>
    <url>http://github.com/FasterXML/StaxMate</url>
    <tag>HEAD</tag>
  </scm>

  <!-- 13-Oct-2020, tatu: Moved to Java 6 baseline (from Java 5) for 2.4 -->
  <!-- 29-May-2026, tatu: and Java 8 for 2.5 -->
  <properties>
    <javac.src.version>8</javac.src.version>
    <javac.target.version>8</javac.target.version>
  </properties>
  
  <issueManagement>
    <url>https://github.com/FasterXML/StaxMate/issues</url>
  </issueManagement>

  <!-- Licensing -->
  <licenses>
    <license>
      <name>BSD</name>
      <url>http://www.opensource.org/licenses/bsd-license.php</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <organization>
    <name>FasterXML</name>
    <url>https://github.com/FasterXML</url>
  </organization>

 <!-- Dependency information -->
 
  <dependencies>

    <!-- 13-Oct-2020, tatu: By now basic Stax2 api should be available on relevant JDKs,
           so drop the explicit dependency
      -->
    <!-- Stax2 API (and matching RI), too, is required, not included,
         We need version 3.x of it to get Typed Access API
      -->
    <dependency>
      <groupId>org.codehaus.woodstox</groupId>
      <artifactId>stax2-api</artifactId>
      <version>4.3.0</version>
    </dependency>

    <!-- and for testing, JUnit is needed -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${version.junit}</version>
      <scope>test</scope>
    </dependency>

    <!-- Ditto for Woodstox -->
    <dependency>
      <groupId>com.fasterxml.woodstox</groupId>
      <artifactId>woodstox-core</artifactId>
      <version>7.1.0</version>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>
       <!-- javadocs? yes please -->
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-javadoc-plugin</artifactId>
          <configuration>
            <encoding>UTF-8</encoding>
            <links>
              <link>https://docs.oracle.com/javase/8/docs/api/</link>
            </links>
          </configuration>
       </plugin>

        <!-- Plus, let's make jars OSGi bundles as well  -->
        <plugin>
          <groupId>org.apache.felix</groupId>
          <artifactId>maven-bundle-plugin</artifactId>
          <extensions>true</extensions>
          <configuration>
            <instructions>
              <Bundle-Name>StaxMate</Bundle-Name>
              <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
              <Bundle-Description>StaxMate -- Perfect companion for your stax processor</Bundle-Description>
              <Bundle-Vendor>FasterXML.com</Bundle-Vendor>
              <Import-Package>
javax.xml*,
org.w3c.dom,
org.codehaus.stax2*
</Import-Package>
              <Private-Package>
org.codehaus.staxmate.util
</Private-Package>
              <Export-Package>
org.codehaus.staxmate,
org.codehaus.staxmate.in,
org.codehaus.staxmate.out,
org.codehaus.staxmate.dom
</Export-Package>
            </instructions>
          </configuration>
        </plugin>

        <!-- Need to configure test task, to skip base classes
          -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <excludes>
              <exclude>**/Base*.java</exclude>
              <exclude>**/*$*.java</exclude>
            </excludes>
            <includes>
              <include>**/Test*.java</include>
            </includes>
          </configuration>
        </plugin>

        <!-- 29-May-2026, tatu: Code coverage (version managed by oss-parent) -->
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <executions>
            <execution>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
            </execution>
            <!-- attached to Maven test phase -->
            <execution>
              <id>report</id>
              <phase>test</phase>
                <goals>
                  <goal>report</goal>
                </goals>
            </execution>
          </executions>
        </plugin>

        <!-- for maven release, need yet another plug-in -->
        <!-- And Sonatype also mandates GPG... -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <configuration>
            <mavenExecutorId>forked-path</mavenExecutorId>
          </configuration>
        </plugin>

    </plugins>
  </build>
</project>
